### ISSUE TITLE
Does not compile with 5.2

### ISSUE THREAD

**Issue by WilliamTys** [Mr-Craig/AsyncTickPhysics#8]

**Comment by Mr-Craig** [comment]
Is it only when packaging your game?

**Comment by WilliamTys** [comment]
Hi. It occurs when packaging the plugin. I've integrated your plugin with
another plugin which requires packaging in this way. I have tested
packaging the ATP plugin in blank project not integrated with any other
plugs and receive these errors.

Kind regards

**Comment by Mr-Craig** [comment]
I was able to package it for 5.2 just needed some header files added:)

**Comment by WilliamTys** [comment]
Thank you so very much! It packages perfectly but there seems to be new
issues when packaging components using these functions. Is there some
includes required for scene components?

SuspensionComponent.h(205): error C2079: 'USuspensionComponent::Hit' uses
undefined struct 'FHitResult'

SuspensionComponent.h(206): error C2079: 'USuspensionComponent::LinearHit'
uses undefined struct 'FHitResult'

SuspensionComponent.cpp(211): error C2027: use of undefined type 'UWorld'

GenericPhysicsInterface.h(10): note: see declaration of 'UWorld'

SuspensionComponent.cpp(219): error C2660:
'UKismetMathLibrary::InverseTransformLocation': function does not take 1
arguments

KismetMathLibrary.inl(964): note: see declaration of
'UKismetMathLibrary::InverseTransformLocation'

Vehicle\SuspensionComponent.cpp(219): note: while trying to match the
argument list '(FTransform)'

SuspensionComponent.cpp(234): error C2027: use of undefined type 'UWorld'

GenericPhysicsInterface.h(10): note: see declaration of 'UWorld'

SuspensionComponent.cpp(256): error C2660:
'UAsyncTickFunctions::ATP_AddForceAtPosition': function does not take 2
arguments

AsyncTickFunctions.h(21): note: see declaration of
'UAsyncTickFunctions::ATP_AddForceAtPosition'

SuspensionComponent.cpp(256): note: while trying to match the argument list
'(UPrimitiveComponent *, UE::Math::TVector<double>)'

SuspensionComponent.cpp(335): error C2440: 'return': cannot convert from
'int' to 'FHitResult'

SuspensionComponent.cpp(335): note: Constructor for struct 'FHitResult' is
declared 'explicit'
